### PR TITLE
Add DBMI related software landscape analysis

### PR DESCRIPTION
**Pull request by d33bs**
This PR adds content for understanding DBMI related software landscape use-cases and potential needs in context with the Software Engineering Team's potential role in supporting the department stakeholders. I focused mostly on languages and SBOM-extracted dependencies but also included data which might be later used for increased / enhanced understanding. The organization YAML data is just a guess - please don't hesitate to let me know if we should cut this down a bit.

Please note: the notebook execution order is a bit out of sorts - the final portions were added last after some development iteration. I open the PR here to honor the time it may take to receive feedback / iterate more (gathering the data takes some time).

Thanks for any thoughts and feedback you may have!

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Really interesting to see the charts. Will review this today.

**Review by vincerubinetti — APPROVED** [review]
Well, I don't see anything blatantly wrong in the code, but I didn't for example check in-depth that you were passing the right arguments to the GitHub API. But it looks right from my past use of the API, and in this case it seems like it would either work correctly or not work at all.

The only thing I could think of is to do some filtering based on whether or not one of us actually contributed to the code? Or perhaps the goal of this was really to get a picture of the whole department and not just us. Either way, I think it gives good enough insights to what we commonly work on and need help with.

**Comment by vincerubinetti** [comment]
One thing, just for my curiosity, can you increase the label size of the absolute counts on the bar charts. I could run the notebook myself but you said it took like 45 min to run from scratch.

**Comment by d33bs** [comment]
Thanks @vincerubinetti ! Great suggestions, I've added some code updates which can allow filtering by GitHub contributor handle and am working on further data gathering. Will follow up with the plot edits and filtering. Also added primary-language-specific dependency plots as discussed verbally (for example, Python specific top dependencies, etc).

**Comment by d33bs** [comment]
Thanks again @vincerubinetti for the PR review here! Merging this in.

**Pull request merged**
